routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Middleware\Admin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//Auth
// Auth::routes();

// // //Home User
// Route::get('/', [App\Http\Controllers\HomeUserController::class, 'index'])->name('/');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('/home');

// Route::middleware('admin')->group(function () {
//     Route::resource('produk', App\Http\Controllers\ProdukController::class);    
// });

// //Start Master Admin
// Route::resource('jenis', App\Http\Controllers\JenisController::class);
// Route::resource('warna', App\Http\Controllers\WarnaController::class);

// // //Cart
// // Route::resource('cart-session', App\Http\Controllers\CartSessionController::class);

// //Cart
// Route::resource('cart', App\Http\Controllers\CartController::class);

Illuminate\Support\Facades\Auth::routes();

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::resource('produk', \App\Http\Controllers\ProdukController::class);
    Route::resource('cart', \App\Http\Controllers\CartController::class);
    Route::resource('transaksi', App\Http\Controllers\TransaksiController::class);
    Route::resource('jenis', App\Http\Controllers\JenisController::class)->except('show');
    Route::resource('warna', App\Http\Controllers\WarnaController::class)->except('show');

app/Models/Jenis.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
Use App\Models\Produk;

class Jenis extends Model
{
    protected $guarded = ['id'];
    protected $table = 'jenis';
    protected $primaryKey = 'id';

    public function produk()
    {
        return $this->hasMany(Produk::class, 'jenis_id', 'id');
    }
}

app/Http/Controllers/JenisController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Jenis;
use Psy\Util\Str;

class JenisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['jenis'] = Jenis::orderBy('jenis','asc')->get();
        return view('admin.jenis.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.jenis.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'jenis' => 'required|unique:jenis',
        ];

        $customMessages = [
            'jenis.required' => 'Jenis wajib diisi!',
            'jenis.unique' => 'Jenis sudah digunakan!',
        ];

        $this->validate($request, $rules, $customMessages);

         //Start Input
         $input = $request->all();
         $status = Jenis::create($input);

         if ($status){
            return redirect()->route('jenis.index')->with('success', 'Data Jenis berhasil ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['jenis'] = Jenis::find($id);
        return view('admin.jenis.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'jenis' => 'required|unique:jenis',
        ];

        $customMessages = [
            'jenis.required' => 'Jenis wajib diisi!',
            'jenis.unique' => 'Jenis sudah digunakan!',
        ];

        $this->validate($request, $rules, $customMessages);

        //Start Input
        $jenis = Jenis::find($id);
        $update = $request->all();
        $status = $jenis->update($update);

        if ($status){
            return redirect()->route('jenis.index')->with('success', 'Data Jenis berhasil diubah');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $jenis = Jenis::find($id);
        $status = $jenis->delete();
        if ($status){
            return 1;
        }else{
            return 0;
        }
    }
}

resources/views/admin/jenis/form.blade.php
@extends('admin.layouts.app')
@section('jenis', 'active')
@section('title')
     Form {{@$jenis ? ' Ubah' : ' Tambah'}}
@endsection
@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Jenis</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('jenis.index')}}">Index</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$jenis ? ' Ubah' : ' Tambah')}} Warna
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    <form class="form form-vertical"  action="{{@$jenis ? route('jenis.update',$jenis->id) : route('jenis.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$jenis)
                                            {{method_field('patch')}}
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="jenis">Jenis</label>
                                                    <input type="text" id="jenis" class="form-control" name="jenis" placeholder="Masukkan Jenis"
                                                    value="{{old('nama', @$jenis ? $jenis->jenis : '')}}"/>
                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                <a href="{{route('jenis.index')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush

resources/views/admin/jenis/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Data Jenis')
@section('jenis', 'active')


@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Jenis</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
{{--                                    <li class="breadcrumb-item"><a href="{{route('jenis.index')}}">jenis</a>--}}
{{--                                    </li>--}}
                                    <li class="breadcrumb-item active">Index
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <div class="row" id="basic-table">
                    <div class="col-12">
                        <div class="card">
                        @can('admin')
                            <div class="card-header">
                                <a href="{{route('jenis.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Tambah Jenis</a>
                            </div>
                            @endcan
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Nama Jenis</th>
                                        <!-- @can('admin') -->
                                        <th>Aksi</th>
                                        <!-- @endcan -->
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($jenis as $row)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$row->jenis}}</td>
                                            <!-- @can('admin') -->
                                            <td>
                                                <a href="{{route('jenis.edit', $row->id)}}" class="btn btn-warning waves-effect waves-float waves-light">Edit</a>
                                                <a href="#" data-id="{{$row->id}}" class="btn btn-danger btn-del waves-effect waves-float waves-light">Delete</a>
                                            </td>
                                            <!-- @endcan -->
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.btn-del', function () {
                var id = $(this).data('id');
                Swal.fire({
                    icon: 'error',
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'error',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                })
                    .then((result) => {
                        if (result.value) {
                            $.ajax({
                                'url': '{{url("jenis")}}/' + id,
                                'type': 'post',
                                'data': {
                                    '_method': 'DELETE',
                                    '_token': '{{csrf_token()}}'
                                },
                                success: function (response) {
                                    if (response == 1) {
                                        toastr.success('Data berhasil dihapus!', 'Berhasil!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                        location.reload();
                                    } else {
                                        toastr.error('Data gagal dihapus!', 'Gagal!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                    }
                                }
                            });
                        } else {
                            console.log(`dialog was dismissed by ${result.dismiss}`)
                        }

                    });
            });

        });

    </script>
@endpush