routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Middleware\Admin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//Auth
// Auth::routes();

// // //Home User
// Route::get('/', [App\Http\Controllers\HomeUserController::class, 'index'])->name('/');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('/home');

// Route::middleware('admin')->group(function () {
//     Route::resource('produk', App\Http\Controllers\ProdukController::class);    
// });

// //Start Master Admin
// Route::resource('jenis', App\Http\Controllers\JenisController::class);
// Route::resource('warna', App\Http\Controllers\WarnaController::class);

// // //Cart
// // Route::resource('cart-session', App\Http\Controllers\CartSessionController::class);

// //Cart
// Route::resource('cart', App\Http\Controllers\CartController::class);

Illuminate\Support\Facades\Auth::routes();

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::resource('produk', \App\Http\Controllers\ProdukController::class);
    Route::resource('cart', \App\Http\Controllers\CartController::class);
    Route::resource('transaksi', App\Http\Controllers\TransaksiController::class);
    Route::resource('jenis', App\Http\Controllers\JenisController::class)->except('show');
    Route::resource('warna', App\Http\Controllers\WarnaController::class)->except('show');

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Transaction;
Use App\Models\Jenis;
Use App\Models\Warna;
Use App\Models\Cart;

class Produk extends Model
{
    protected $guarded = ['id'];
    protected $table = 'produks';
    protected $primaryKey = 'id';

    public function jenis()
    {
        return $this->belongsTo(Jenis::class);
    }

    public function warna()
    {
        return $this->belongsTo(Warna::class);
    }

    public function cart(){
        return $this->belongsTo(Cart::class);
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Produk;
use App\Models\Jenis;
use App\Models\Warna;
use App\Models\Cart;
use App\Models\Total;
use App\Models\CartDetail;

use Illuminate\Support\Facades\Auth;

class ProdukController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Res
     *
     *ponse
     */
    public function index()
    {
        $data['produk'] = Produk::all();
        $data['keranjang'] = Cart::where('user_id', '=', Auth::user()->id)->get();
        $data['total'] = $data['keranjang']->sum('subtotal');

        return view('admin.produk.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function data()
    // {
    //     $datas = Produk::with(['jenis', 'detail'])->get();
    //     // dd($datas);
    //     return view('data', compact('datas'));
    // }
    public function create()
    {
        $data['jenis'] = Jenis::all();
        $data['warna'] = Warna::all();
        return view('admin.produk.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'deskripsi' => 'required',
            'spesifikasi' => 'required',
            'stok' => 'required|numeric', 
            'hpp' => 'required',
            'harga_jual' => 'required',
            'foto_produk' => 'required',
            'foto_produk.*' => 'image|mimes:jpeg,png,jpg|max:2048'
        ]);

        $imageName = time() . '.' . $request->foto_produk->extension();
        $request->foto_produk->move(public_path() . '/image/foto_produk/', $imageName);

        Produk::create([
            'nama' => $request['nama'],
            'jenis_id' => $request['jenis_id'],
            'warna_id' => $request['warna_id'],
            'stok' => $request['stok'],
            'deskripsi' => $request['deskripsi'],
            'spesifikasi' => $request['spesifikasi'],
            'hpp' => $request['hpp'],
            'harga_jual' => $request['harga_jual'], 
            'foto_produk' => $imageName,
        ]);

        // $customMessages = [
        //     'nama.required' => 'Produk wajib diisi!',
        //     'deskripsi.required' => 'Deskrpsi wajib diisi',
        //     'spesifikasi.required' => 'Spesifikasi wajib diisi',
        //     'stok.required' => 'Stok wajib diisi',
        //     'hpp.required' => 'HPP wajib diisi!',
        //     'harga_jual.required' => 'Harga wajib diisi!',
        //     'foto_produk.required' => 'Foto wajib diisi!',
        // ];

        // $this->validate($customMessages);

        return redirect()->route('produk.index')->with('success', 'Data Produk berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['produk'] = Produk::findOrFail($id);
        return view('admin.produk.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['jenis'] = Jenis::all();
        $data['produk']= Produk::find($id);
        $data['warna'] = Warna::all();

        return view('admin.produk.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required|string',
            'jenis_id' => 'required',
            'warna_id' => 'required',
            'deskripsi' => 'required',
            'spesifikasi' => 'required',
            'stok' => 'required|numeric',
            'hpp' => 'required|numeric',
            'harga_jual' => 'required|numeric',
        ]);

        $produk = Produk::find($id);

        if ($request->foto_produk){
            $imageName = time() . '.' . $request->foto_produk->extension();
            $request->foto_produk->move(public_path() . '/image/foto_produk/', $imageName);
        } else {
            $imageName = $produk->foto_produk;
        }

        $produk = $produk->update([
            'nama' => $request['nama'],
            'jenis_id' => $request['jenis_id'],
            'warna_id' => $request['warna_id'],
            'deskripsi' => $request['deskripsi'],
            'spesifikasi' => $request['spesifikasi'],
            'stok' => $request['stok'],
            'hpp' => $request['hpp'],
            'harga_jual' => $request['harga_jual'],
            'foto_produk' => $imageName,
        ]);

        return redirect()->route('produk.index')->with('success', 'Data Produk berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produk = Produk::find($id);
        $status = $produk->delete();
        if ($status){
            return 1;
        }else{
            return 0;
        }
    }
}

resources/views/admin/produk/form-detail.blade.php
@extends('admin.layouts.app')
@section('ukulele', 'active')

@section('title')
    Form {{@$produk ? ' Ubah' : ' Tambah'}}
@endsection
@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Produk</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('produk-detail.index')}}">Index</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$produk ? ' Ubah Detail' : ' Tambah Detail')}} Produk
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    <form class="form form-vertical"  action="{{@$produk ? route('produk-detail.update',1) : route('produk-detail.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$produk)
                                            {{method_field('patch')}}
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="warna_id">Warna</label>
                                                    <select class="form-select form-control" id="warna_id" name="warna_id" >
                                                        <option value="">- Pilih Warna Produk -</option>
                                                        @foreach($warna as $row)
                                                            <option value="{{$row->id}}" {{@$produk && $produk->warna_id == $row->id ? 'selected' : '' }}>{{$row->warna}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="stok">Stok</label>
                                                    <input type="number" min="0" id="stok" class="form-control" name="stok" placeholder="10"
                                                           value="{{old('stok', @$produk ? $produk->stok : '')}}">
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="deskripsi">Deskripsi</label>
                                                    <textarea type="text" class="form-control" name="deskripsi" value="">{{old('deskripsi', @$produk ? $produk->deskripsi : '')}}</textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="spesifikasi">Spesifikasi</label>
                                                    <textarea type="text" class="form-control" name="spesifikasi" value="">{{old('spesifikasi', @$produk ? $produk->spesifikasi : '')}}</textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="foto_produk">Foto Produk</label>
                                                    <input type="file" id="foto_produk" class="form-control" name="foto_produk" placeholder=""
                                                           value="{{old('foto_produk', @$produk ? $produk->foto_produk : '')}}">
                                                </div>
                                            </div>


                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                <a href="{{route('produk-detail.index')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                            </div>
                                        </div>
                                    </form>


                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush

resources/views/admin/produk/form.blade.php
@extends('admin.layouts.app')
@section('ukulele','active')

@section('title')
    Form {{@$produk ? ' Ubah' : ' Tambah'}}
@endsection
@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Produk</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('produk.index')}}">Index</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$produk ? ' Ubah' : ' Tambah')}} produk
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    <form class="form form-vertical"  action="{{@$produk ? route('produk.update', $produk->id) : route('produk.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$produk)
                                            {{method_field('patch')}}
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="nama">Nama</label>
                                                    <input type="text" id="produk" class="form-control" name="nama" placeholder="Nama"
                                                           value="{{old('nama', @$produk ? $produk->nama : '')}}"/>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="jenis_id">Jenis</label>
                                                    <select class="form-select form-control" id="jenis_id" name="jenis_id" >
                                                        <option value="">- Pilih Jenis Produk -</option>
                                                        @foreach($jenis as $row)
                                                            <option value="{{$row->id}}" {{@$produk && $produk->jenis_id == $row->id ? 'selected' : '' }}>{{$row->jenis}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="warna_id">Warna</label>
                                                    <select class="form-select form-control" id="warna_id" name="warna_id" >
                                                        <option value="">- Pilih Warna Produk -</option>
                                                        @foreach($warna as $row)
                                                            <option value="{{$row->id}}" {{@$produk && $produk->warna_id == $row->id ? 'selected' : '' }}>{{$row->warna}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="deskripsi">Deskripsi</label>
                                                    <textarea type="text" class="form-control" name="deskripsi" value="">{{old('deskripsi', @$produk ? $produk->deskripsi : '')}}</textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="spesifikasi">Spesifikasi</label>
                                                    <textarea type="text" class="form-control" name="spesifikasi" value="">{{old('spesifikasi', @$produk ? $produk->spesifikasi : '')}}</textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="foto_produk">Foto Produk</label>
                                                    <input type="file" id="foto_produk" class="form-control" name="foto_produk" placeholder=""
                                                           value="{{old('foto_produk', @$produk ? $produk->foto_produk : '')}}">
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="stok">Stok</label>
                                                    <input type="number" min="0" id="stok" class="form-control" name="stok" placeholder="10"
                                                           value="{{old('stok', @$produk ? $produk->stok : '')}}">
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="hpp">Hpp</label>
                                                    <input type="number" min="0" id="hpp" class="form-control" name="hpp" placeholder="100000"
                                                           value="{{old('hpp', @$produk ? $produk->hpp : '')}}"/>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="harga_jual">Harga</label>
                                                    <input type="number" min="0" id="harga_jual" class="form-control" name="harga_jual" placeholder="100000"
                                                           value="{{old('harga_jual', @$produk ? $produk->harga_jual : '')}}"/>
                                                </div>
                                            </div>


                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                <a href="{{route('produk.index')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                            </div>
                                        </div>
                                    </form>


                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush 